concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "cloudserver runner"
  url = "https://gitlab.com/"
  token = "INSERT TOKEN HERE"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
  [runners.docker]
    tls_verify = false
    image = "docker:19.03.8"
    privileged = true
    disable_cache = false
    volumes = ["/certs/client", "/cache"]
