image: docker:19.03.8

variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build

services:
  - docker:19.03.8-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build --tag project-demo:latest project-demo/.
